### ISSUE TITLE
is it possible to persist the readers 'book finished' status in calibre?

### ISSUE THREAD

**Issue by reuschling** [wold5/calibre-pocketbook-tools#2]
I search for a possibility to persist the 'read' status of a book inside my pocketbook reader. Perfect would be also to set the 'read' status of a book inside calibre.
Is this possible with this plugin? I'm not exactly sure - the screenshots say that a database from the reader is backuped. Is the read status inside? Do you know which database is used from pockedbook? Maybe SQLLite?

Thanks for answering newbie questions :)

**Comment by wold5** [comment]
Hi, for setting just the 'completed' status on a device, you can try the "pocketbook collection manager", see: 
https://github.com/anareaty/PocketBook_Collection_Manager
https://www.mobileread.com/forums/showthread.php?t=334784
There's also the official PocketBook Cloud Sync service.

But no, this plug-in (pockettools) doesn't handle completed/progress reading states. It mainly allows a backup of the databases. The read state/progress data are stored in the "explorer-3.db", a SQLite3 file. "Calibre-annotations" has logic for (only) reading PB annotations (see my commits), but does nothing with read states AFAIK. As an aside, a GUI tool for restoring backups is in the works, but it's a separate program (not a plugin), like the collection manager. 

If you have any questions, feel free to ask.
